using Mutagen.Bethesda;
using Mutagen.Bethesda.Synthesis;
using Mutagen.Bethesda.Skyrim;

namespace MissivesSynthesisPatcher
{
    public class PatcherSettings
    {
        public List<string> FormIDsToRemove { get; set; } = new();
    }

    public class Program
    {
        static Lazy<PatcherSettings> Settings = null!;

        public static async Task<int> Main(string[] args)
        {
            return await SynthesisPipeline.Instance
                .AddPatch<ISkyrimMod, ISkyrimModGetter>(RunPatch)
                .SetAutogeneratedSettings(
                    nickname: "Settings",
                    path: "settings.json",
                    out Settings)
                .Run(args);
        }

        public static void RunPatch(IPatcherState<ISkyrimMod, ISkyrimModGetter> state)
        {
            var settings = Settings.Value;
            var formKeysToRemove = new HashSet<Mutagen.Bethesda.Plugins.FormKey>();
            
            Console.WriteLine($"FormIDs to remove: {string.Join(", ", settings.FormIDsToRemove)}");
            
            foreach (var formIdStr in settings.FormIDsToRemove)
            {
                if (Mutagen.Bethesda.Plugins.FormKey.TryFactory(formIdStr, out var formKey))
                {
                    formKeysToRemove.Add(formKey);
                    Console.WriteLine($"Parsed FormID: {formIdStr} -> {formKey}");
                }
                else
                {
                    Console.WriteLine($"ERROR: Could not parse FormID: {formIdStr}");
                }
            }

            Console.WriteLine($"Total FormKeys to remove: {formKeysToRemove.Count}");

            foreach (var formlistGetter in state.LoadOrder.PriorityOrder.FormList().WinningOverrides())
            {
                var formlistOverride = state.PatchMod.FormLists.GetOrAddAsOverride(formlistGetter);

                Console.WriteLine($"\nProcessing formlist: {formlistGetter.EditorID}");
                Console.WriteLine($"Items before: {formlistOverride.Items.Count}");

                for (int i = 0; i < formlistOverride.Items.Count; i++)
                {
                    Console.WriteLine($"  {i}: {formlistOverride.Items[i].FormKey}");
                }

                int removedCount = 0;
                for (int i = formlistOverride.Items.Count - 1; i >= 0; i--)
                {
                    var itemFormKey = formlistOverride.Items[i].FormKey;
                    if (formKeysToRemove.Contains(itemFormKey))
                    {
                        Console.WriteLine($"Removing: {itemFormKey}");
                        formlistOverride.Items.RemoveAt(i);
                        removedCount++;
                    }
                }

                Console.WriteLine($"Items removed: {removedCount}");
                Console.WriteLine($"Items after: {formlistOverride.Items.Count}");
            }
        }
    }
}

