using Mutagen.Bethesda;
using Mutagen.Bethesda.Synthesis;
using Mutagen.Bethesda.Skyrim;

namespace MissivesSynthesisPatcher
{
    public class PatcherSettings
    {
        public List<string> EditorIDsToRemove { get; set; } = new();
    }

    public class Program
    {
        static Lazy<PatcherSettings> Settings = null!;

        public static async Task<int> Main(string[] args)
        {
            return await SynthesisPipeline.Instance
                .AddPatch<ISkyrimMod, ISkyrimModGetter>(RunPatch)
                .SetAutogeneratedSettings(
                    nickname: "Settings",
                    path: "settings.json",
                    out Settings)
                .Run(args);
        }

        public static void RunPatch(IPatcherState<ISkyrimMod, ISkyrimModGetter> state)
        {
            var settings = Settings.Value;
            var removedItems = new List<(string FormlistEditorID, string ItemEditorID, string ItemFormKey)>();
            
            Console.WriteLine($"EditorIDs to remove: {string.Join(", ", settings.EditorIDsToRemove)}");

            foreach (var formlistGetter in state.LoadOrder.PriorityOrder.FormList().WinningOverrides())
            {
                Console.WriteLine($"\nProcessing formlist: {formlistGetter.EditorID}");
                Console.WriteLine($"Items before: {formlistGetter.Items.Count}");

                for (int i = 0; i < formlistGetter.Items.Count; i++)
                {
                    var itemFormKey = formlistGetter.Items[i].FormKey;
                    var itemRecord = state.LinkCache.Resolve(itemFormKey);
                    var itemEditorID = itemRecord.EditorID ?? "";
                    Console.WriteLine($"  {i}: {itemFormKey} ({itemEditorID})");
                }

                int removedCount = 0;
                var itemsToRemove = new List<int>();
                
                for (int i = formlistGetter.Items.Count - 1; i >= 0; i--)
                {
                    var itemFormKey = formlistGetter.Items[i].FormKey;
                    var itemRecord = state.LinkCache.Resolve(itemFormKey);
                    var itemEditorID = itemRecord.EditorID ?? "";

                    foreach (var searchPattern in settings.EditorIDsToRemove)
                    {
                        if (itemEditorID.Contains(searchPattern, StringComparison.OrdinalIgnoreCase))
                        {
                            Console.WriteLine($"Removing: {itemFormKey} ({itemEditorID})");
                            removedItems.Add((formlistGetter.EditorID ?? "Unknown", itemEditorID, itemFormKey.ToString()));
                            itemsToRemove.Add(i);
                            removedCount++;
                            break;
                        }
                    }
                }

                if (removedCount > 0)
                {
                    var formlistOverride = state.PatchMod.FormLists.GetOrAddAsOverride(formlistGetter);
                    foreach (var index in itemsToRemove)
                    {
                        formlistOverride.Items.RemoveAt(index);
                    }
                }

                Console.WriteLine($"Items removed: {removedCount}");
                Console.WriteLine($"Items after: {formlistGetter.Items.Count - removedCount}");
            }

            // Print summary
            Console.WriteLine($"\n{'='} REMOVAL SUMMARY {'='}\n");
            if (removedItems.Count == 0)
            {
                Console.WriteLine("No items were removed.");
            }
            else
            {
                Console.WriteLine($"Total items removed: {removedItems.Count}\n");
                var groupedByFormlist = removedItems.GroupBy(x => x.FormlistEditorID);
                foreach (var group in groupedByFormlist)
                {
                    Console.WriteLine($"From formlist '{group.Key}':");
                    foreach (var item in group)
                    {
                        Console.WriteLine($"  - {item.ItemFormKey} ({item.ItemEditorID})");
                    }
                    Console.WriteLine();
                }
            }
        }
    }
}

