using Mutagen.Bethesda;
using Mutagen.Bethesda.Synthesis;
using Mutagen.Bethesda.Skyrim;

namespace MissivesSynthesisPatcher
{
    public class PatcherSettings
    {
        public List<string> EditorIDsToRemove { get; set; } = new();
    }

    public class Program
    {
        static Lazy<PatcherSettings> Settings = null!;

        public static async Task<int> Main(string[] args)
        {
            return await SynthesisPipeline.Instance
                .AddPatch<ISkyrimMod, ISkyrimModGetter>(RunPatch)
                .SetAutogeneratedSettings(
                    nickname: "Settings",
                    path: "settings.json",
                    out Settings)
                .Run(args);
        }

        public static void RunPatch(IPatcherState<ISkyrimMod, ISkyrimModGetter> state)
        {
            var settings = Settings.Value;
            
            Console.WriteLine($"EditorIDs to remove: {string.Join(", ", settings.EditorIDsToRemove)}");

            foreach (var formlistGetter in state.LoadOrder.PriorityOrder.FormList().WinningOverrides())
            {
                var formlistOverride = state.PatchMod.FormLists.GetOrAddAsOverride(formlistGetter);

                Console.WriteLine($"\nProcessing formlist: {formlistGetter.EditorID}");
                Console.WriteLine($"Items before: {formlistOverride.Items.Count}");

                for (int i = 0; i < formlistOverride.Items.Count; i++)
                {
                    var itemFormKey = formlistOverride.Items[i].FormKey;
                    var itemRecord = state.LinkCache.Resolve(itemFormKey);
                    var itemEditorID = itemRecord.EditorID ?? "";
                    Console.WriteLine($"  {i}: {itemFormKey} ({itemEditorID})");
                }

                int removedCount = 0;
                for (int i = formlistOverride.Items.Count - 1; i >= 0; i--)
                {
                    var itemFormKey = formlistOverride.Items[i].FormKey;
                    var itemRecord = state.LinkCache.Resolve(itemFormKey);
                    var itemEditorID = itemRecord.EditorID ?? "";

                    foreach (var searchPattern in settings.EditorIDsToRemove)
                    {
                        if (itemEditorID.Contains(searchPattern, StringComparison.OrdinalIgnoreCase))
                        {
                            Console.WriteLine($"Removing: {itemFormKey} ({itemEditorID})");
                            formlistOverride.Items.RemoveAt(i);
                            removedCount++;
                            break;
                        }
                    }
                }

                Console.WriteLine($"Items removed: {removedCount}");
                Console.WriteLine($"Items after: {formlistOverride.Items.Count}");
            }
        }
    }
}

